# Generated by Django 4.2.5 on 2023-10-27 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('otp', models.IntegerField()),
                ('role', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=False)),
                ('is_verify', models.BooleanField(default=True)),
                ('is_created', models.DateTimeField(auto_now_add=True)),
                ('is_updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AddmissionForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merit_no', models.IntegerField(max_length=50)),
                ('mht_cet', models.IntegerField(max_length=50)),
                ('seat_no_hsc', models.IntegerField(max_length=50)),
                ('marks_hsc', models.IntegerField(max_length=50)),
                ('percentage_hsc', models.IntegerField(max_length=50)),
                ('name_of_board', models.CharField(max_length=50)),
                ('prev_clg_name', models.CharField(max_length=50)),
                ('stud_photo', models.ImageField(upload_to='app/images.Candidate')),
                ('sign_photo', models.ImageField(upload_to='app/images.Candidate')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('fathers_name', models.CharField(max_length=50)),
                ('mothers_name', models.CharField(max_length=50)),
                ('parents_full_name', models.CharField(max_length=50)),
                ('paddress', models.CharField(max_length=80)),
                ('pstate', models.CharField(max_length=50)),
                ('pdistrict', models.CharField(max_length=50)),
                ('ppincode', models.IntegerField(max_length=10)),
                ('occupation', models.CharField(max_length=50)),
                ('yearly_income', models.IntegerField(max_length=50)),
                ('pmobile', models.IntegerField(max_length=50)),
                ('laddress', models.CharField(max_length=100)),
                ('lstate', models.CharField(max_length=50)),
                ('ldistrict', models.CharField(max_length=50)),
                ('lpincode', models.IntegerField(max_length=10)),
                ('stud_email', models.CharField(max_length=50)),
                ('stud_mob', models.IntegerField(max_length=50)),
                ('place_of_birth', models.CharField(max_length=50)),
                ('nationality', models.CharField(max_length=50)),
                ('mhstate', models.CharField(max_length=50)),
                ('religion', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('cast', models.CharField(max_length=50)),
                ('pcm_mrks', models.IntegerField(max_length=10)),
                ('phy_mrks', models.IntegerField(max_length=50)),
                ('chem_mrks', models.IntegerField(max_length=50)),
                ('maths_mrks', models.IntegerField(max_length=50)),
                ('other_mrks', models.IntegerField(max_length=50)),
                ('total_fees', models.IntegerField(max_length=50)),
                ('recipt_no', models.IntegerField(max_length=50)),
                ('adhar_no', models.IntegerField(max_length=50)),
                ('pan_no', models.IntegerField(max_length=50)),
                ('s_board', models.CharField(max_length=50)),
                ('s_year_of_passing', models.IntegerField(max_length=50)),
                ('s_mrks', models.IntegerField(max_length=50)),
                ('s_outof', models.IntegerField(max_length=50)),
                ('s_percentage', models.IntegerField(max_length=50)),
                ('h_board', models.CharField(max_length=50)),
                ('h_year_of_passing', models.IntegerField(max_length=50)),
                ('h_mrks', models.IntegerField(max_length=50)),
                ('h_outof', models.IntegerField(max_length=50)),
                ('h_percentage', models.IntegerField(max_length=50)),
                ('hostel_fees', models.IntegerField(max_length=50)),
                ('recipt', models.IntegerField(max_length=50)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usermaster')),
            ],
        ),
    ]
