# Generated by Django 4.2.5 on 2023-10-29 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_usermaster_alter_addmissionform_sign_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Can',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=50)),
                ('Lastname', models.CharField(max_length=50)),
                ('merit_no', models.IntegerField()),
                ('mht_cet', models.IntegerField()),
                ('seat_no_hsc', models.IntegerField()),
                ('marks_hsc', models.IntegerField()),
                ('percentage_hsc', models.IntegerField()),
                ('name_of_board', models.CharField(max_length=50)),
                ('prev_clg_name', models.CharField(max_length=50)),
                ('stud_photo', models.ImageField(upload_to='app/images/Candidate')),
                ('sign_photo', models.ImageField(upload_to='app/images/Candidate')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('fathers_name', models.CharField(max_length=50)),
                ('mothers_name', models.CharField(max_length=50)),
                ('parents_full_name', models.CharField(max_length=50)),
                ('paddress', models.CharField(max_length=80)),
                ('pstate', models.CharField(max_length=50)),
                ('pdistrict', models.CharField(max_length=50)),
                ('ppincode', models.IntegerField()),
                ('occupation', models.CharField(max_length=50)),
                ('yearly_income', models.IntegerField()),
                ('pmobile', models.IntegerField()),
                ('laddress', models.CharField(max_length=100)),
                ('lstate', models.CharField(max_length=50)),
                ('ldistrict', models.CharField(max_length=50)),
                ('lpincode', models.IntegerField()),
                ('stud_email', models.CharField(max_length=50)),
                ('stud_mob', models.IntegerField()),
                ('place_of_birth', models.CharField(max_length=50)),
                ('nationality', models.CharField(max_length=50)),
                ('mhstate', models.CharField(max_length=50)),
                ('religion', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('cast', models.CharField(max_length=50)),
                ('pcm_mrks', models.IntegerField()),
                ('phy_mrks', models.IntegerField()),
                ('chem_mrks', models.IntegerField()),
                ('maths_mrks', models.IntegerField()),
                ('other_mrks', models.IntegerField()),
                ('total_fees', models.IntegerField()),
                ('recipt_no', models.IntegerField()),
                ('adhar_no', models.IntegerField()),
                ('pan_no', models.IntegerField()),
                ('s_board', models.CharField(max_length=50)),
                ('s_year_of_passing', models.IntegerField()),
                ('s_mrks', models.IntegerField()),
                ('s_outof', models.IntegerField()),
                ('s_percentage', models.IntegerField()),
                ('h_board', models.CharField(max_length=50)),
                ('h_year_of_passing', models.IntegerField()),
                ('h_mrks', models.IntegerField()),
                ('h_outof', models.IntegerField()),
                ('h_percentage', models.IntegerField()),
                ('hostel_fees', models.IntegerField()),
                ('recipt', models.IntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usermaster')),
            ],
        ),
        migrations.RemoveField(
            model_name='candiadate',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='AddmissionForm',
        ),
        migrations.DeleteModel(
            name='Candiadate',
        ),
    ]
